backend:
  name: git-gateway
  branch: master
media_folder: "static/assets"
public_folder: "assets"

collections:
  - name: "leg" # Used in routes, e.g., /admin/collections/blog
    label: "Leg" # Used in the UI
    folder: "src/pages/leg" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publish-date", widget: "datetime" }
      - { label: "Start Date", name: "start-date", widget: "datetime" }
      - { label: "End Date", name: "end-date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Gallery",
          name: "galleryImages",
          widget: "list",
          required: false,
          field: { label: Image, name: image, widget: image, required: false },
        }

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "site/content/home.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "Crew"
        name: "crew"
        file: "site/content/crew.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Locations
            name: locations
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Address, name: address, widget: string }
